# .github/workflows/devsecops-pipeline.yml

name: Django DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  SONAR_HOST_URL: http://localhost:9000

jobs:
  lint-and-typecheck:
    name: Lint & Type-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        continue-on-error: true

      - name: Install lint & type-check tools
        run: |
          pip install "importlib-metadata<6.0.0"
          pip install flake8 pylint mypy
        continue-on-error: true

      - name: Flake8 lint (exclude env & libs)
        run: |
          flake8 . \
            --exclude=venv,.venv,env,lib,site-packages,__pycache__ \
            --max-line-length=88
        continue-on-error: true

      - name: Pylint (skip venv)
        run: |
          pylint **/*.py \
            --ignore-patterns="venv/*,.venv/*,env/*,lib/*,site-packages/*"
        continue-on-error: true

      - name: Mypy type-check (exclude venv)
        run: |
          mypy . \
            --exclude 'venv|\.venv|env|lib|site-packages|__pycache__'
        continue-on-error: true

  security-scan:
    name: Static Security Scans
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        continue-on-error: true

      - name: Install SAST & dependency tools
        run: pip install bandit semgrep safety
        continue-on-error: true

      - name: Bandit scan (exclude env & libs)
        run: |
          mkdir -p reports
          bandit -r . \
            -x venv,env,lib,site-packages,__pycache__ \
            -f json -o reports/bandit.json
        continue-on-error: true

      - name: Semgrep scan (exclude env & libs)
        run: |
          semgrep --config=p/ci \
            --json --output=reports/semgrep.json \
            --exclude-dir=venv,env,lib,site-packages,__pycache__
        continue-on-error: true

      - name: Safety dependency scan
        run: safety check -r requirements.txt --json > reports/safety.json
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
        continue-on-error: true

  container-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .
        continue-on-error: true

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:${{ github.sha }}
        continue-on-error: true

  dast-scan:
    name: Dynamic App Security Test
    runs-on: ubuntu-latest
    needs: container-scan
    services:
      webapp:
        image: myapp:${{ github.sha }}
        ports:
          - 8000:8000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Install OWASP ZAP
        run: sudo snap install zaproxy --classic
        continue-on-error: true

      - name: Run ZAP full scan
        run: |
          zaproxy -daemon -port 8090 -host 0.0.0.0
          zap-full-scan.py -t http://localhost:8000 -r reports/zap-report.html
        continue-on-error: true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/zap-report.html
        continue-on-error: true

  sonar-scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: dast-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        continue-on-error: true

      - name: Download SonarScanner
        run: |
          curl -sSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip \
            -o sonar-scanner.zip
          unzip -q sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
        continue-on-error: true

      - name: Make scanner executable
        run: chmod +x ./sonar-scanner/bin/sonar-scanner
        continue-on-error: true

      - name: Run SonarScanner (exclude env & libs)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectKey=proiect-django \
            -Dsonar.sources=. \
            -Dsonar.exclusions=**/venv/**,**/env/**,**/lib/**,**/site-packages/**,**/__pycache__/** \
            -Dsonar.externalIssuesReportPaths=reports/sonar-bandit.json,reports/sonar-semgrep.json,reports/sonar-safety.json \
            -X
        continue-on-error: true
